Repository spring-petclinic/spring-petclinic-rest, pull requests merged in 2025-02, with the labels that each got.

#189 Customize maven configuration
  .gitignore
  pom.xml
Labels: dependencies

#193 SonarCloud : configure Jacoco XML format and add badges
  .github/workflows/maven-build-master.yml
  .github/workflows/maven-build-pull-request.yml
  .github/workflows/maven-build.yml
  pom.xml
  readme.md
Labels: enhancement

#195 Fix Java compiler version to 17 and remove duplicated maven plugin versions #194
  pom.xml
Labels: bug

#197 Ensure API readiness for JMeter testing
  pom.xml
  readme.md
  src/main/resources/application.properties
Labels: documentation

#201 Updates Swagger @Configuration class
  src/main/java/org/springframework/samples/petclinic/config/SwaggerConfig.java
  terms.txt
Labels: enhancement

#200 Introduce H2 as the Default In-Memory Database for Local Development & Testing
  pom.xml
  readme.md
  src/main/resources/application-h2.properties
  src/main/resources/application.properties
  src/main/resources/db/h2/data.sql
  src/main/resources/db/h2/schema.sql
Labels: enhancement

#202 Small fixes on README
  readme.md
Labels: documentation

#203 Add JMeter Performance Test for Spring PetClinic REST API
  readme.md
  src/test/jmeter/README.md
  src/test/jmeter/petclinic-jmeter-crud-benchmark.jmx
Labels: enhancement, documentation
