Repository spring-petclinic/spring-petclinic-rest, pull requests merged in 2025-04, with the labels that each got.

#215 Added missing context root to h2 console URL
  readme.md
Labels: documentation

#217 Extending first and lastname patterns #148
  .gitignore
  src/main/resources/openapi.yml
Labels: enhancement

#216 Remove the POST endpoint from the /api/pets ressource
  readme.md
  src/main/java/org/springframework/samples/petclinic/rest/controller/PetRestController.java
  src/main/resources/openapi.yml
  src/test/java/org/springframework/samples/petclinic/rest/controller/PetRestControllerTests.java
Labels: bug

#218 Applying MapStruct compiler options only during main compilation
  pom.xml
Labels: bug

#219 Adding Non-Regression Tests with Postman for "First Visit" scenario
  postman-tests.sh
  readme.md
  src/test/postman/README.md
  src/test/postman/petclinic-env.postman_environment.json
  src/test/postman/petclinic-nonregressiontests.postman_collection.json
Labels: enhancement

#221 Adding missing PUT method in OwnerRestController class With Integration Tests
  src/main/java/org/springframework/samples/petclinic/rest/controller/OwnerRestController.java
  src/test/java/org/springframework/samples/petclinic/rest/controller/OwnerRestControllerTests.java
Labels: bug

#222 Adding a second postman scenario, improving & fixing shell script, updating gitignore & postman readme
  .gitignore
  postman-tests.sh
  src/test/postman/README.md
  src/test/postman/petclinic-nonregressiontests.postman_collection.json
Labels: enhancement

#223 Adding CI Workflow to Run Postman Tests with Newman
  .github/workflows/newman-pipeline.yml
  postman-tests.sh
  src/test/postman/petclinic-nonregressiontests.postman_collection.json
Labels: enhancement
